version: '3.9'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: secret
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: